### ISSUE TITLE
Compatible with shairport-sync or mopidy?

### ISSUE THREAD

**Issue by pronsta** [RanzQ/hyperion-audio-effects#21]
Hi,

I just want to ask if somebody already created something like hyperion audio effects with shairport-sync or mopidy? 

Thanks

**Comment by RanzQ** [comment]
I've personally tested this on Pi2 with mpd (mopidy is basically the same) so that should work. Shairport-sync readme says "it must have direct access to the output device" and that might be a problem. With Kodi for example that prevents the use of a virtual loopback device.

Anyway, if you have a hardware that supports looping the signal back for monitoring, there should be no problem.

**Comment by pronsta** [comment]
hey thanks for the reply. I have a cheap usb sound card called C-media how do i know if they support the loopback signal? or can you recommend a external sound card with who supports it?

**Comment by RanzQ** [comment]
@pronsta Cheap sound cards usually don't support it. It is usually exposed as a device called "What you hear" or "Stereo Mix".

But according to this, shairport should work with virtual loobpack: https://github.com/mikebrady/shairport-sync/issues/249
